### PR TITLE
MIN: Fix conformance, correctness and consistency issues in docs

### PR DESCRIPTION
**Pull request by CAM-Gerlach**
While I was at it, I figured I'd fix some low-hanging fruit conformance and correctness issues I found in the repo. This is still [WiP], since I'm awaiting a merge on #5 to avoid a conflict and keep things clean. I committed the changes in rough order of likelihood of any potential disagreement/ease of reverting, so I can more easily drop any commits if any aren't desired by the project maintainers for a good reason.

Specifically this PR:
* Adds a terminating EOL to files missing it, as it is officially required for properly formed text files particularly on Mac/Linux/Unix OSes, and a number of programs (particularly command-line and programming tools) will break or not operate correctly. It also avoids Git raising a warning every time ``git diff`` is run on the files.
* Converts date representation(s) to the international, unambiguous ISO 8601 format, which avoids issues with locale-specific dates (as was currently used) and is a standard convention in programming/science/engineering
* Strips unneeded trailing whitespace from the files that have it, to avoid future merge conflicts and other inconsistencies as many editors do this by default, as well as a moderate savings in file size
* Converts a few instances of tabs instead of spaces for consistency (as most code is in spaces, not tabs), to conform to PEP 8 and the reST specification (which strongly recommends spaces instead of tabs and converts to spaces on input), and avoid twice the width being inserted in the final document as intended and apparent in most editors (as reST/docutils assumes a tab width of 8 spaces by default).
* Upgrades several missed links to HTTPS (after first confirming no difference in functionality vs. the HTTP version), and updates a few broken/redirected links
* Conforms all files to consistent EOLs (LF), which avoids the current mix of EOLs (most LF but some CRLF), reduces file size, avoids Git constantly adding spurious <kbd>M</kbd> indications to every changed line, ensures consistency across all platforms, avoids any problem with command-line tools, and conforms to general best practices.
* Adds a ``.gitattributes`` file, which enforces EOL consistency and sensible default behavior across platforms (will be commited after previous is unblocked)
* Adds a basic ``.gitignore`` file, with common language-independent and reST/Sphinx/Python specific ignores  (will be commited after previous is unblocked)

Thanks, and let me know your feedback.

Last steps:

* [x] Rebase after #5 
* [x] Convert GettingStarted to LF
* [x] Add Gitattributes
* [x] Add Gitignore

### CODE REVIEW

**Review by kmuehlbauer — APPROVED** [review]
@CAM-Gerlach We very much appreciate this effort. I haven't spotted any problems so far. LGTM.

**Comment by CAM-Gerlach** [comment]
@kmuehlbauer Thanks! Finishing it up now...

**Comment by CAM-Gerlach** [comment]
Okay, done on my end!

**Comment by kmuehlbauer** [comment]
@CAM-Gerlach Perfect. Looking into it next day.

**Comment by kmuehlbauer** [comment]
@heistermann Could you have a last look? I'm about to pull this in.

**Review by heistermann — APPROVED** [review]
Thanks a lot!

**Comment by kmuehlbauer** [comment]
@CAM-Gerlach Thanks for your contribution!

**Pull request merged**
